install.packages("tidyverse")
install.packages("rmarkdown")
install.packages('BCEA')
install.packages('rjags')
install.packages("R2OpenBUGS")
install.packages("R2jags")
remotes::install_github("giabaio/bmhe_utils")  
