options(timeout=2600)
install.packages("tidyverse")
install.packages("here")
install.packages("rmarkdown")
install.packages("remotes")
install.packages('BCEA')
install.packages('rjags')
install.packages("R2OpenBUGS")
remotes::install_github("giabaio/R2jags",ref="bmhta")
install.packages("bmhe", repos = c("https://giabaio.r-universe.dev", "https://cloud.r-project.org"))
install.packages("survHE")
install.packages("INLA",repos=c(getOption("repos"),INLA="https://inla.r-inla-download.org/R/testing"), dep=TRUE) 
# Needs the R-forge version of MatrixModels or else INLA will break
install.packages("MatrixModels",repos="https://r-forge.r-project.org/")
install.packages("survHEinla", repos = c("https://giabaio.r-universe.dev", "https://cloud.r-project.org"))
